[zh]
    label  = "简体中文"
    title  = "我的博客"
    weight = 1

    [zh.params.sidebar]
        subtitle = "记录并分享日常"

[en]
    label  = "English"
    title  = "My Blog"
    weight = 2

    [en.params.sidebar]
        subtitle = "Notes and daily life"
